title: FoxBox Wiki
description: Wiki on what you can do in the server.
theme: just-the-docs
color_scheme: dark

url: https://foxboxmc.github.io/wiki
baseurl: "/wiki"
url: "https://just-the-docs.com"
repository: FoxBoxMC/wiki

logo: "/assets/images/logo.png"
favicon_ico: "/assets/images/logo.ico"

heading_anchors: true

permalink: pretty

back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Copyright &copy; 2017-2020 Patrick Marsceill. Distributed by an <a href=\"https://github.com/just-the-docs/just-the-docs/tree/main/LICENSE.txt\">MIT license.</a> <a href=\"https://www.netlify.com/\">This site is powered by Netlify.</a>"

last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/FoxBoxMC/wiki"
gh_edit_branch: "main"
gh_edit_view_mode: "edit"

aux_links_new_tab: true

aux_links:
  Main Site: https://foxboxmc.net
