title: FoxBox Wiki
description: Wiki on what you can do in the server.
theme: just-the-docs

url: https://foxboxmc.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
